name: workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'

jobs: 
    itegration:
        name: Continous Integration
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Lint Code
            run: echo "Linting repository"

          - name: Run unit tests
            run: echo "Running unit tests"


